name: Generate GitHub Metrics

on:
  schedule:
    # Runs every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # GitHub authentication
          token: ${{ secrets.GITHUB_TOKEN }}

          # Your GitHub username
          user: adrienbelcastro

          # Output file
          filename: metrics.svg

          # Basic metrics
          template: classic
          base: header, activity, community, repositories

          # Appearance
          config_timezone: America/Toronto

          # Optional: show more details
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used

          plugin_stars: yes
          plugin_followup: yes
